import streamlit as st
import pandas as pd
import numpy as np
import plotly.express as px
from sklearn.ensemble import IsolationForest

# Page configuration
st.set_page_config(
    page_title="Network Fault Detection",
    page_icon="📡",
    layout="wide"
)

st.title("📡 Real-Time Network Fault Detection")
st.subheader("AI-Based Network Operations Monitoring Dashboard")

# Sidebar settings
st.sidebar.header("Monitoring Settings")

samples = st.sidebar.slider(
    "Number of telemetry samples",
    100,
    1000,
    300
)

contamination = st.sidebar.slider(
    "Anomaly sensitivity",
    0.01,
    0.15,
    0.05
)

# Generate telemetry
if st.button("Generate Telemetry & Detect Anomalies"):

    np.random.seed(42)

    df = pd.DataFrame({
        "CPU": np.random.normal(50, 12, samples),
        "Memory": np.random.normal(60, 10, samples),
        "Latency": np.random.normal(40, 8, samples),
        "Traffic": np.random.normal(500, 100, samples)
    })

    # Add simulated abnormal events
    fault_indices = np.random.choice(
        samples,
        size=max(1, int(samples * 0.03)),
        replace=False
    )

    df.loc[fault_indices, "Latency"] += 100
    df.loc[fault_indices, "CPU"] += 35

    # Machine Learning model
    model = IsolationForest(
        contamination=contamination,
        random_state=42
    )

    features = ["CPU", "Memory", "Latency", "Traffic"]

    df["Prediction"] = model.fit_predict(df[features])

    # Assign Normal and Anomaly labels
    df["Status"] = df["Prediction"].map({
        1: "Normal",
        -1: "Anomaly"
    })

    # Sample number
    df.insert(0, "Sample", range(1, samples + 1))

    # Separate records
    normal = df[df["Status"] == "Normal"]
    anomalies = df[df["Status"] == "Anomaly"]

    # Dashboard metrics
    st.subheader("📊 Network Monitoring Results")

    col1, col2, col3, col4 = st.columns(4)

    col1.metric("Total Samples", len(df))

    col2.metric("Normal Records", len(normal))

    col3.metric("Anomalies Detected", len(anomalies))

    col4.metric(
        "Anomaly Percentage",
        f"{len(anomalies) / len(df) * 100:.2f}%"
    )

    # Network latency graph
    st.subheader("🌐 Network Latency Monitoring")

    fig = px.scatter(
        df,
        x="Sample",
        y="Latency",
        color="Status",
        color_discrete_map={
            "Normal": "green",
            "Anomaly": "red"
        },
        title="Normal vs Anomalous Network Latency",
        hover_data=["CPU", "Memory", "Traffic", "Prediction"]
    )

    fig.update_traces(marker=dict(size=8))

    st.plotly_chart(fig, use_container_width=True)

    # Complete dataset
    st.subheader("📋 Complete Network Telemetry")

    st.dataframe(
        df,
        use_container_width=True
    )

    # Normal records
    st.subheader("✅ Normal Network Records")

    st.success(f"{len(normal)} Normal records detected")

    st.dataframe(
        normal,
        use_container_width=True
    )

    # Anomaly records
    st.subheader("🚨 Detected Network Anomalies")

    if len(anomalies) > 0:

        st.error(
            f"⚠️ {len(anomalies)} Potential network anomalies detected!"
        )

        st.dataframe(
            anomalies,
            use_container_width=True
        )

    else:
        st.success("No anomalies detected.")

    # Download results
    csv = df.to_csv(index=False).encode("utf-8")

    st.download_button(
        label="⬇️ Download Complete Results CSV",
        data=csv,
        file_name="network_fault_detection.csv",
        mime="text/csv"
    )

    st.info(
        "This application uses simulated network telemetry. "
        "Normal and Anomaly labels are generated by the Isolation Forest model."
    )

else:

    st.info(
        "Click the button to generate simulated telemetry "
        "and detect network anomalies."
    )